import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import {Providers} from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Philippine Scripts Translator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en" data-theme="translator">

        <body className={inter.className}>
        <Providers>

          <div className="bg-b-navy">
            <Header />
            <div>{children}</div>
          </div>
          </Providers>
        </body>
      </html>
  );
}
